#!/usr/bin/env bash
#
#SBATCH --job-name=Hotspot
#SBATCH --time=72:00:00
#SBATCH --output=hotspot_%A_%a.out
#SBATCH --error=hotspot_%A_%a.err
#SBATCH --cpus-per-task=1
#SBATCH --exclude=iforgot
#SBATCH --oversubscribe
#SBATCH --array=0-11

CONFIG=example

RODINIA=(backprop bfs b+tree dwt2d gaussian heartwall hotspot kmeans lavaMD lud myocyte nw)

bm=$((${SLURM_ARRAY_TASK_ID} % 12))
bm=${RODINIA[${bm}]}

POWER_DIR=ptraces
OUT_DIR=outputs

 ../../hotspot -c example.config -p ptraces/${WORKLOAD}.ptrace -materials_file example.materials -grid_layer_file example.lcf -model_type grid -detailed_3D on -use_microchannels 1 -steady_file outputs/${WORKLOAD}.steady -grid_steady_file outputs/${WORKLOAD}.grid.steady
cp ${OUT_DIR}/${bm}.steady ${OUT_DIR}/${bm}.init
../../hotspot -c example.config -init_file ${OUT_DIR}/${WORKLOAD}.init -p ptraces/${WORKLOAD}.ptrace -materials_file example.materials -grid_layer_file example.lcf -model_type grid -detailed_3D on -use_microchannels 1 -o outputs/${WORKLOAD}.ttrace -grid_transient_file outputs/${WORKLOAD}.grid.ttrace -grid_steady_file outputs/${WORKLOAD}.grid.steady
